<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xgfwwo\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xgfwwo/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/Container6xgfwwo.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\Container6xgfwwo\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \Container6xgfwwo\EccubeProdProjectContainer([
    'container.build_hash' => '6xgfwwo',
    'container.build_id' => 'e94ff066',
    'container.build_time' => 1624595812,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xgfwwo');
