<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4y6cy7d\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4y6cy7d/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/Container4y6cy7d.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\Container4y6cy7d\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \Container4y6cy7d\EccubeProdProjectContainer([
    'container.build_hash' => '4y6cy7d',
    'container.build_id' => '49257f45',
    'container.build_time' => 1623946303,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4y6cy7d');
