<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNtsfxv1\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNtsfxv1/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNtsfxv1.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerNtsfxv1\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerNtsfxv1\EccubeProdProjectContainer([
    'container.build_hash' => 'Ntsfxv1',
    'container.build_id' => '0e139d4e',
    'container.build_time' => 1624377995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNtsfxv1');
